/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:9bdb7ea1-d312-461f-b71c-f673fd9883f3",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_McxKD52bV",
    "aws_user_pools_web_client_id": "6f24v0ne773d68ubqfda6s260v",
    "oauth": {}
};


export default awsmobile;
